# Uncomment the next line to define a global platform for your project


platform :osx, '10.14'
source 'https://github.com/CocoaPods/Specs.git'

target 'KSKit' do
  use_frameworks!

pod "SnapKit", "~> 4.2.0"
pod 'Alamofire'
#pod 'MBProgressHUD'



 
end
